backend:
  name: proxy
  url: http://localhost:8081/api

local_backend: true

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Category", name: "category", widget: "select", options: ["Strategy", "Data Management", "Leadership", "Innovation", "Data"]}
      - {label: "Read Time", name: "readTime", widget: "string", default: "5 min read"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list", field: {label: "Tag", name: "tag", widget: "string"}}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Subtitle", name: "heroSubtitle", widget: "string"}
          - {label: "Hero Description", name: "heroDescription", widget: "text"}
          - {label: "Services Title", name: "servicesTitle", widget: "string"}
          - {label: "Services Description", name: "servicesDescription", widget: "text"}
          - {label: "Service 1 Title", name: "service1Title", widget: "string"}
          - {label: "Service 1 Description", name: "service1Description", widget: "text"}
          - {label: "Service 2 Title", name: "service2Title", widget: "string"}
          - {label: "Service 2 Description", name: "service2Description", widget: "text"}
          - {label: "Service 3 Title", name: "service3Title", widget: "string"}
          - {label: "Service 3 Description", name: "service3Description", widget: "text"}

      - file: "content/pages/data-management.md"
        label: "Data Management Page"
        name: "data-management"
        fields:
          - {label: "Hero Title", name: "heroTitle", widget: "string"}
          - {label: "Hero Description", name: "heroDescription", widget: "text"}
          - {label: "Section 1 Title", name: "section1Title", widget: "string"}
          - {label: "Section 1 Content", name: "section1Content", widget: "markdown"}
          - {label: "Section 2 Title", name: "section2Title", widget: "string"}
          - {label: "Section 2 Content", name: "section2Content", widget: "markdown"}
          - {label: "Section 3 Title", name: "section3Title", widget: "string"}
          - {label: "Section 3 Content", name: "section3Content", widget: "markdown"}

      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Contact Email", name: "email", widget: "string"}
          - {label: "Contact Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}
          - {label: "Page Title", name: "pageTitle", widget: "string"}
          - {label: "Page Description", name: "pageDescription", widget: "text"}

      - file: "content/pages/site-settings.md"
        label: "Site Settings"
        name: "site-settings"
        fields:
          - {label: "Site Title", name: "siteTitle", widget: "string"}
          - {label: "Site Description", name: "siteDescription", widget: "text"}
          - {label: "Contact Email", name: "contactEmail", widget: "string"}
          - {label: "Contact Phone", name: "contactPhone", widget: "string"}
          - {label: "Footer Tagline", name: "footerTagline", widget: "string"}
          - {label: "Footer Description", name: "footerDescription", widget: "text"}
